### PR TITLE
Fixed a bug that caused conductivity readings to occasionallly come out garbled.

### PR DESCRIPTION
**Pull request by KW-M**
Hello Open CTD folks!

I'm building open CTDs for the Seafloor Science & ROV summer camp in Monterey, California. We are hoping to use the CTDs in activities with highschool students where they do their own coastal ocean reaserch project and learn about different sensors and data analysis methods along the way.

When I got data back from my first Open CTD, some of the conductivity values had weird characters in the numbers.
I figured out the issue was with the timing of the conductivity sensor serial messages and temperature probe signals, and I fixed that bug in this branch. 

As far as I can tell this code doesn't have any changes to cause problems with other CTD setups. I put specific things I changed in the commit messages.

Thanks!

Here was my setup:
Addalogger m0
Mini Atlas Scientific conductivity Probe attached to the ezo conductivity circuit board.
The 3 temperature probes
Small pressure sensor (no Sparkfun board)

### CODE REVIEW

**Review by IanTBlack — COMMENTED** [review]
Andrew,

I don't have a way to test this, but this should be implemented. Typically I just hard code the conversion delays in my stuff. 

EC EZO conversion time is 600ms in I2C mode. It is unclear if this is the same in UART mode, but should be easy to test. It says 1s in the datasheet, so it may be a circuit thing.

MS5803 ADC conversion takes at most 9.04 ms at highest resolution. I agree with KW-M that the highest resolution should be used for the pressure sensor. Could just hard code it to 10ms to make it easier. 

The DS18B20 takes 750ms at the highest resolution. 

Conceivably, the max sampling rate could be 1.33Hz if you get the EC EZO and pressure sensor to sample within the 750ms delay. Personally, I don't see any advantage to going faster than 1Hz.

- Ian

**Review by IanTBlack — COMMENTED** [review]
Hi Kyle,

Based on your commit comment (item #1), I would recommend sampling temperature before EC. There is functionality on the EC EZO that allows you to pipe in temperature for a more accurate conductivity reading (if you want to implement that). Alternatively, you could employ a temperature correction equation on the board or after you pull the data off.

Cheers,
- Ian

**Comment by KW-M** [comment]
Hi Ian,

Thanks for replying so fast!
As far as I could tell, the EC EZO just sends the conductivity measurements around 1-second intervals (or whatever interval you set) so I couldn't figure out how to guarantee the timing didn't overlap without just doing the temp measurement after the EC measurement. I do like your second suggestion though. I will look into that!

**Comment by IanTBlack** [comment]
Hi Kyle,

Here is a sketch that I had written for Andrew a while back. It might have some stuff you can use. I don't use the MS5803 and DS18B20, so you might need to tweak it to work.

https://github.com/IanTBlack/CTDizzle/tree/master/kyle

- Ian

**Comment by KW-M** [comment]
Hi Ian,
That code looks super helpful. Thanks!
I thought about trying I2C mode for the EC EZO like you did, but that would also be a hardware wiring switch for Open CTD, so I didn't go there. Also, I hadn't really looked at CTDizzle, It seems very similar. Does Dizzle = Open CTD V2?

**Comment by DrAndrewThaler** [comment]
Hello,

Thank you! (And thanks, Ian, as well). This is really fantastic and I don't see any conflicts with the main code. I'll run it through the paces on our test platform this weekend to make sure there's no conflicts and then merge the pull. We also found that the conductivity data is noisier if the EC circuit power isn't isolated from the rest of the assembly. I'm putting in a fresh PCB order with the new circuit layout sometime in the next week, so if you want to email me a shipping address, I'll send one of the prototype boards your way.

**Comment by KW-M** [comment]
Great! Let me know if anything comes up in the tests. 
If you're looking for people to test the PCB version, I'd love to build and test one! Our end goal is to make several CTDs so groups of students or camps could put CTDs in different places. We've been looking at how to add aditional sensors like light or O2 (if we can get the interface to work).  Extensibility is one of the benifits of the breadboard design now, but if the PCB design (maybe v2) had pinnouts for spare feather pins, that would be great for users who might want flexiblity.

**Pull request merged**
